language: node_js
node_js:
  - 12

deploy:
  provider: heroku
  api_key:
    secure: IwtBLgEsUAUI83u8nGLupnbHXQjH/y/oNK8eJNX20bCBVTu9kft+RTOrFXy1A6zw4S9TsXwjbqI8eqYjH4oiQeLcGphqolyFIdskUxLnpbaeK1LZlDvtXyxdjPcS1BXPT4YgPuxHuHp8lGJAWKGAdDs5XIPnrXTHP1cyocFkzH9z96j9sSkS4w3U1srqAMRCnShBvwRqk0aIozw908WBlSB2IfRiLgvdNRhnJNNCO3xm7NWboolOYJOjHV8MEhi9zkGu8GI/FhnMKIP2nYdFoUVkebZDe8tSnQ+dl8XIf+DIcCwga1WFfFN35TZBFCcXVsfdUH4KHjn04bwrYXANH64kdTGwh0ps4V6KKXBRelurpJgrHYwSHke3mYzSVDzl9VUWg6O7v4sZSVXmnStI1UrgwVw5gvkpzIOo53HDAhwjVvoAZyhLBcLGNbOiLy3a0VnePPPzMsvxt2lFwPKVrIhzn+SWoA+2CXBSfb5xbiUZB2aPihugcsg2pNJyUdcqwJOfzmxYiC+pCG39Ae0NyjNji9Hx+RCIQSxAlzH+NED2JtXurlsw62jvRTTDhdekpmkILN9iLTZGHcJPChQzUzoFs/td7uLG39tU4WtLXYUtHWVvVjCAqDAIP+/L7gL57nyEqYtkai1561fqp7k0hjkEA0a1WMnGu9N4NaH6EgA=
  on:
    branch: master
  run:
    - "yarn build"
    - "yarn install"
    - "yarn postinstall"
    - "yarn knex:migrate"
    - "yarn knex:seed"

notifications:
  email: false